### ISSUE TITLE
No module named gym.envs.registration

### ISSUE THREAD

**Issue by mayuce** [Souphis/gym-vrep#1]
Hello, first thanks for this repo. I'm trying to install gym-vrep everything is OK untill I try run ipython __init__.py on terminal it show me an error about Importing gym error. How does this library works ? When I try it on pycharm it shows no error but nothing happens. Help me please.

Here is the error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/supreme/gym-vrep/gym_vrep/__init__.py in <module>()
      1 import logging
----> 2 from gym.envs.registration import register
      3 
      4 logger = logging.getLogger(__name__)
      5 register(

ImportError: No module named gym.envs.registration

**Comment by gbartyzel** [comment]
Hello!
I have never encountered with such error. But it seems that your python env cannot find gym library. Try this:
1. open ipython
2. import gym
3. import gym_vrep

If this didn't work, you should check if gym is installed in pip.

**Comment by gbartyzel** [comment]
Also, you could check this repo https://github.com/Souphis/mobile_robot_rl. In this project I used gym-vrep.

**Comment by mayuce** [comment]
Okay, I'll try it as soon as possible, thanks.

**Comment by YuanBoXie** [comment]
Hello, I have the same problem, but I don't use gym_ vrep library, so this problem may not be related to the library, but to the gym version or something others.
The gym version on my computer is 0.10.5, but the project I use is multi-agent particle environment which has dependency on the gym version is also 0.10.5.

**Comment by gbartyzel** [comment]
@hexbo Ok, thanks for pointing this, I will update the requirements and maybe this will solve this
