### ISSUE TITLE
Qt Aborted (core dumped)

### ISSUE THREAD

**Issue by zfwang615** [Souphis/gym-vrep#10]
Hi, Souphis! First thanks for this repo. I'm trying to install gym-vrep everything is OK until I try to run simple_run.py on vscode. It shows me an error about Qt. 
Here is the error:
`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/jack/anaconda3/envs/pyt38/lib/python3.8/site-packages/cv2/qt/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Aborted (core dumped)
`

After install Qt5, I got a similar error. It shows me that `... Qt plugin "xcb" is found but can nott be used ...`

**Comment by gbartyzel** [comment]
The solution is to donwgrade opencv-python to version 4.2.*.*. I have encountered same problem when setting up new environment. Try this and let me know if this fixed a problem.

**Comment by zfwang615** [comment]
> The solution is to donwgrade opencv-python to version 4.2._._. I have encountered same problem when setting up new environment. Try this and let me know if this fixed a problem.

Oh, it works well on simplerun.py after downgrading the opencv-python from 4.5 to 4.2. Thank you for your help! I‘m sorry to reply so late. I worked on another project's deadline last week and forgot to check the mail.
