### ISSUE TITLE
Error when running the simple examle

### ISSUE THREAD

**Issue by P4STA** [Souphis/gym-vrep#13]
I'm trying to run the provided example. 
I'm on a fresh install of Ubuntu 20 in virtual box. 
All dependencies installed. When trying to run the simple_run.py in VS Code I get this error: 

`Exception has occurred: TypeError
ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
  File "/home/vvv/gym-vrep/examples/simple_run.py", line 7, in main
    env = gym.make("DynamicRoomNavigation-v0")
  File "/home/vvv/gym-vrep/examples/simple_run.py", line 20, in <module>
    main()`
    
And this is in terminal:

`cd /home/vvv/gym-vrep ; /usr/bin/env /bin/python3 /home/vvv/.vscode/extensions/ms-python.python-2022.6.2/pythonFiles/lib/python/debugpy/launcher 35247 -- /home/vvv/gym-vrep/examples/simple_run.py 
/usr/local/lib/python3.8/dist-packages/gym_coppelia_sim-0.2.0-py3.8.egg/gym_coppelia_sim/envs/mobile_robot_navigation/mobile_robot_navigation.py:230: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  velocities = np.array([0.0, -max_angular_vel])
/usr/local/lib/python3.8/dist-packages/gym_coppelia_sim-0.2.0-py3.8.egg/gym_coppelia_sim/envs/mobile_robot_navigation/mobile_robot_navigation.py:253: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  velocities = np.array([max_linear_vel, max_angular_vel])`
  
Do I need to modify the mobile_robot_navigation.py somehow just to get the simple_run.py to do something?

**Comment by gbartyzel** [comment]
@P4STA bug is fixed, you can try this now ;)
