### ISSUE TITLE
pıoneer robot

### ISSUE THREAD

**Issue by jooker23** [Souphis/gym-vrep#9]
how can i change robot? for example i changed the smartbot to pıoneer robot . when the pıoneer robot hit obstacles, the episode cant change to new episode. how can i fix it?

**Comment by gbartyzel** [comment]
Yeah, to changed the robot you have to implement robot class just like in the smartbot. So, the pioneer robot class should be like the smart bot class. I think that I can adjust this class to be compatible with diffrent robots, but of course you can create a pull request as well ;)
